spring :
  application:
    name: eureka-server

swagger :
  title : 'eureka-server'
  version : '1.0'
  license : 'Wang Zi Qing'

#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: 111111
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    status-page-url: http://120.76.84.114:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZosane: http://120.76.84.114:8762/eureka/
    fetch-registry: false
    register-with-eureka: false

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    status-page-url: http://120.76.84.114:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://120.76.84.114:8761/eureka/